### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by skyliner1123** [fireFerry/byob-bot#36]
![issue](https://user-images.githubusercontent.com/103896565/163872124-078ea58b-85f6-4382-9d08-946702939d2e.PNG)

I keep getting this error when running "sudo python3 Run.py"

**Comment by fireFerry** [comment]
This is a [BYOB](https://github.com/malwaredllc/byob) issue, and doesn't have to do with BYOB-Bot, the Discord bot of the server.
